### ISSUE TITLE
Handling submodule changes between commits

### ISSUE THREAD

**Issue by edahlseng** [leoheck/kdiff#17]
The team I work on uses Git submodules for our component libraries. Sometimes a single commit does nothing but change a submodule commit reference. It would be great if those changes could also be viewable in this tool (note that we don't store the -cache files in Git).

How could this be supported? Would a shallow checkout of the repository need to be made for each commit, include submodules, in order to generate images against a full working copy of the repository?

This is related to #14, but distinct. While it appears that plotgitsch doesn't currently support libraries, it looks like KiCad-Diff does, and so solving this would at least allow submodule changes to propagate through for board layouts.

**Comment by leoheck** [comment]
I am closing this for now due to the lack of activity. Feel free to reopen it if needed.

**Comment by edahlseng** [comment]
@leoheck thanks for following up here, I’m sorry I never responded.

You’re right that if nothing is changed in the layout file, then a library update doesn’t affect anything. I had my mental model wrong and thought that wasn’t the case. I now see that my question here only applies to schematics if a cache file isn’t used, but there’s more work to be done to support that use case anyways.
