### ISSUE TITLE
empty `title`, `revision`, `date` html fields 

### ISSUE THREAD

**Issue by maholli** [leoheck/kdiff#19]
First off, I've been loving this tool! Thank you for streamlining kidiff and plotgitsch, it's a pleasure to use.

Minor error I have is a few html fields aren't populating. See pic below:
![image](https://user-images.githubusercontent.com/29153441/141663983-b91696a7-c4a7-4040-9281-ef675ffc59a0.png)

I tried fiddling with the bash, like [here](https://github.com/leoheck/kdiff/blob/01a20b4c8fcf2a66ddc849e44c28851ca3bfd9c6/kdiff#L863), but all I can determine is `$title == ""` is returning `true`, but not sure why. Looks like you're just extracting it from the filename, right?

- using WSL2

Any tips would be appreciated. 😄

**Comment by leoheck** [comment]
Hi. This tool started from the layout. This means this data comes from the layout page. Could you check if that filling this information on PC new page solves your problem?

**Comment by maholli** [comment]
Ah! I had only set these in the schematic and never knew the layout also had separate definitions. 

That solved it. Thank you!!

**Comment by leoheck** [comment]
Glad that it helped. Thanks for the feedback. I will have to check if it is
possible to keep it updated with the schematic too.

**Comment by leoheck** [comment]
Hey, @maholli could you test the latest version on master? I improved this info. When showing the layout it shows info from the layout, and when showing the schematics, it shows the info from the schematics.

Hope it works for you.

![image](https://user-images.githubusercontent.com/1277920/142081668-d26e7c5c-a81e-4f6e-a025-cbac0dd2ebc6.png)
![image](https://user-images.githubusercontent.com/1277920/142081697-bbc70581-aa7d-49bb-bd59-ee76f656208f.png)
