### ISSUE TITLE
Zooming/Pan on PCB layout

### ISSUE THREAD

**Issue by jorlee99** [leoheck/kdiff#3]
I can't seem to zoom in or Pan when looking at PCB's and it seems that the view buttons don't work either when looking at the PCB layout.

**Comment by leoheck** [comment]
Yeap, this is not working fine yet. Just use your mouse/trackpad for now it will work better.

**Comment by jorlee99** [comment]
It seems that even using the mouse/trackpad isn't working for the PCB layout. It works just fine for the schematic view but only has problems during the PCB layout. I recall it working before as well.

**Comment by leoheck** [comment]
You are correct, let me check if I can fix this.

**Comment by leoheck** [comment]
Please, check if it is fixed now.

**Comment by jorlee99** [comment]
Yup it works again thanks!
