### ISSUE TITLE
Plotgitsch is not working fine for nested projects

### ISSUE THREAD

**Issue by leoheck** [leoheck/kdiff#4]
When projects have the same schematic name, gitplottsch does not work fine.

**Comment by jorlee99** [comment]
It seems to work fine for both tests
![image](https://user-images.githubusercontent.com/43526839/118549439-521e2880-b710-11eb-9357-aa45b3afb71e.png)
![image](https://user-images.githubusercontent.com/43526839/118549460-5b0efa00-b710-11eb-9f8e-c185f521cf6b.png)
I'll show you my file structure
https://gitlab.com/jordan.lee1202/nested_test

**Comment by leoheck** [comment]
Thanks.
Plotgitsch has this issue where if it does not find a part, it gives an exception and do not generate the image. I don't know how to solve this. Ocaml is so hard to change something.

**Comment by leoheck** [comment]
Thanks. Then I will close this for now.
